<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 public/Model.glb --types
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	ref = new Group();

	type ActionName = 'Edgar.Armature' | 'Edgar.Armature.001' | 'Camera.001' | 'Door.001' | 'Lid.001';
	type GLTFResult = {
		nodes: {
			GlassesModel001: THREE.Mesh;
			Cube016: THREE.SkinnedMesh;
			Cube016_1: THREE.SkinnedMesh;
			Cube016_2: THREE.SkinnedMesh;
			Cube016_3: THREE.SkinnedMesh;
			Cube016_4: THREE.SkinnedMesh;
			Cube016_5: THREE.SkinnedMesh;
			TieModel001: THREE.SkinnedMesh;
			Floor001: THREE.Mesh;
			Wall1001: THREE.Mesh;
			Wall2001: THREE.Mesh;
			Roof001: THREE.Mesh;
			Wall3001: THREE.Mesh;
			Door001: THREE.Mesh;
			Knob1001: THREE.Mesh;
			Knob2001: THREE.Mesh;
			WindowFrame1001: THREE.Mesh;
			WindowFrame2001: THREE.Mesh;
			Wall4001: THREE.Mesh;
			WindowFrame3001: THREE.Mesh;
			WindowFrame4001: THREE.Mesh;
			Grass001: THREE.Mesh;
			Road001: THREE.Mesh;
			RoadPainting001: THREE.Mesh;
			MailboxBase001: THREE.Mesh;
			Cube027: THREE.Mesh;
			Cube027_1: THREE.Mesh;
			Lid001: THREE.Mesh;
			Opener001: THREE.Mesh;
			Pillar001: THREE.Mesh;
			Surface001: THREE.Mesh;
			Hip_1: THREE.Bone;
			LeftShoulder_1: THREE.Bone;
			RightShoulder_1: THREE.Bone;
			LeftForeleg_1: THREE.Bone;
			RightForeleg_1: THREE.Bone;
		};
		materials: {
			Glasses: THREE.MeshStandardMaterial;
			Material: THREE.MeshStandardMaterial;
			Flesh: THREE.MeshStandardMaterial;
			Hair: THREE.MeshStandardMaterial;
			Pants: THREE.MeshStandardMaterial;
			Shoes: THREE.MeshStandardMaterial;
			Shirt: THREE.MeshStandardMaterial;
			Tie: THREE.MeshStandardMaterial;
			OneSidedFloor: THREE.MeshStandardMaterial;
			OneSidedWall: THREE.MeshStandardMaterial;
			SolidWall: THREE.MeshStandardMaterial;
			Wood: THREE.MeshStandardMaterial;
			Gold: THREE.MeshStandardMaterial;
			WindowFrame: THREE.MeshStandardMaterial;
			OneSidedGrass: THREE.MeshStandardMaterial;
			Asphalt: THREE.MeshStandardMaterial;
			RoadPainting: THREE.MeshStandardMaterial;
			Mailbox: THREE.MeshStandardMaterial;
			Void: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/Model.glb');

	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="TestScene">
			<T.Group name="EdgarArmature001" position={[-0.13, -0.29, 0]} rotation={[0, Math.PI / 2, 0]}>
				<T is={gltf.nodes.Hip_1} />
				<T is={gltf.nodes.LeftShoulder_1} />
				<T is={gltf.nodes.RightShoulder_1} />
				<T is={gltf.nodes.LeftForeleg_1} />
				<T is={gltf.nodes.RightForeleg_1} />
				<T.Group name="EdgarModel001">
					<T.SkinnedMesh
						name="Cube016"
						geometry={gltf.nodes.Cube016.geometry}
						material={gltf.materials.Material}
						skeleton={gltf.nodes.Cube016.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube016_1"
						geometry={gltf.nodes.Cube016_1.geometry}
						material={gltf.materials.Flesh}
						skeleton={gltf.nodes.Cube016_1.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube016_2"
						geometry={gltf.nodes.Cube016_2.geometry}
						material={gltf.materials.Hair}
						skeleton={gltf.nodes.Cube016_2.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube016_3"
						geometry={gltf.nodes.Cube016_3.geometry}
						material={gltf.materials.Pants}
						skeleton={gltf.nodes.Cube016_3.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube016_4"
						geometry={gltf.nodes.Cube016_4.geometry}
						material={gltf.materials.Shoes}
						skeleton={gltf.nodes.Cube016_4.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube016_5"
						geometry={gltf.nodes.Cube016_5.geometry}
						material={gltf.materials.Shirt}
						skeleton={gltf.nodes.Cube016_5.skeleton}
					/>
				</T.Group>
				<T.SkinnedMesh
					name="TieModel001"
					geometry={gltf.nodes.TieModel001.geometry}
					material={gltf.materials.Tie}
					skeleton={gltf.nodes.TieModel001.skeleton}
				/>
			</T.Group>
			<T.Group name="NurbsPath" />
			<T.PerspectiveCamera
				name="Camera001"
				far={100}
				near={0.1}
				fov={22.9}
				position={[15.66, 0.23, 16.06]}
				rotation={[0.01, 0.77, -0.01]}
        makeDefault
			/>
			<T.Mesh
				name="Floor001"
				geometry={gltf.nodes.Floor001.geometry}
				material={gltf.materials.OneSidedFloor}
				position={[0, -1.8, 0]}
			/>
			<T.Mesh
				name="Wall1001"
				geometry={gltf.nodes.Wall1001.geometry}
				material={gltf.materials.OneSidedWall}
				position={[4, 0.5, 0]}
			/>
			<T.Mesh
				name="Wall2001"
				geometry={gltf.nodes.Wall2001.geometry}
				material={gltf.materials.OneSidedWall}
				position={[0, 0.5, 4]}
			/>
			<T.Mesh
				name="Roof001"
				geometry={gltf.nodes.Roof001.geometry}
				material={gltf.materials.OneSidedFloor}
				position={[0, 2.8, 0]}
			/>
			<T.Mesh
				name="Wall3001"
				geometry={gltf.nodes.Wall3001.geometry}
				material={gltf.materials.SolidWall}
				position={[0.55, 0.85, -4]}
			>
				<T.Mesh
					name="Door001"
					geometry={gltf.nodes.Door001.geometry}
					material={gltf.materials.Wood}
					position={[3.37, -0.65, 0.12]}
					rotation={[0, -1.54, 0]}
				>
					<T.Mesh
						name="Knob1001"
						geometry={gltf.nodes.Knob1001.geometry}
						material={gltf.materials.Gold}
						position={[0.01, 0, 1.39]}
					/>
					<T.Mesh
						name="Knob2001"
						geometry={gltf.nodes.Knob2001.geometry}
						material={gltf.materials.Gold}
						position={[-0.36, 0, 1.38]}
					/>
				</T.Mesh>
				<T.Mesh
					name="WindowFrame1001"
					geometry={gltf.nodes.WindowFrame1001.geometry}
					material={gltf.materials.WindowFrame}
					position={[-1.26, 0.22, 0]}
				/>
				<T.Mesh
					name="WindowFrame2001"
					geometry={gltf.nodes.WindowFrame2001.geometry}
					material={gltf.materials.WindowFrame}
					position={[0.17, 0.22, 0]}
				/>
			</T.Mesh>
			<T.Mesh
				name="Wall4001"
				geometry={gltf.nodes.Wall4001.geometry}
				material={gltf.materials.SolidWall}
				position={[-4, 0.5, 0]}
			>
				<T.Mesh
					name="WindowFrame3001"
					geometry={gltf.nodes.WindowFrame3001.geometry}
					material={gltf.materials.WindowFrame}
					position={[0, 0.58, 0.72]}
				/>
				<T.Mesh
					name="WindowFrame4001"
					geometry={gltf.nodes.WindowFrame4001.geometry}
					material={gltf.materials.WindowFrame}
					position={[0, 0.58, -0.72]}
				/>
			</T.Mesh>
			<T.Mesh
				name="Grass001"
				geometry={gltf.nodes.Grass001.geometry}
				material={gltf.materials.OneSidedGrass}
				position={[0, -1.9, 0]}
			/>
			<T.Mesh
				name="Road001"
				geometry={gltf.nodes.Road001.geometry}
				material={gltf.materials.Asphalt}
				position={[0, -1.8, -17.88]}
			>
				<T.Mesh
					name="RoadPainting001"
					geometry={gltf.nodes.RoadPainting001.geometry}
					material={gltf.materials.RoadPainting}
					position={[0, 0.1, 0]}
				/>
			</T.Mesh>
			<T.Mesh
				name="MailboxBase001"
				geometry={gltf.nodes.MailboxBase001.geometry}
				material={gltf.materials.Wood}
				position={[0, -0.15, -6.31]}
			>
				<T.Group name="Mailbox001" position={[0, 1.08, -0.55]}>
					<T.Mesh
						name="Cube027"
						geometry={gltf.nodes.Cube027.geometry}
						material={gltf.materials.Mailbox}
					/>
					<T.Mesh
						name="Cube027_1"
						geometry={gltf.nodes.Cube027_1.geometry}
						material={gltf.materials.Void}
					/>
					<T.Mesh
						name="Lid001"
						geometry={gltf.nodes.Lid001.geometry}
						material={gltf.materials.Mailbox}
						position={[0, -0.17, -0.45]}
					/>
					<T.Mesh
						name="Opener001"
						geometry={gltf.nodes.Opener001.geometry}
						material={gltf.materials.Mailbox}
						position={[-0.2, 0.2, -0.23]}
					/>
				</T.Group>
				<T.Mesh
					name="Pillar001"
					geometry={gltf.nodes.Pillar001.geometry}
					material={gltf.materials.Wood}
					position={[0, 0.44, -0.36]}
				/>
				<T.Mesh
					name="Surface001"
					geometry={gltf.nodes.Surface001.geometry}
					material={gltf.materials.Wood}
					position={[0, 0.8, -0.25]}
				/>
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
