<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 public/models/model/testscene2.glb --types
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	ref = new Group();

	type ActionName = 'Edgar.Armature' | 'Camera' | 'Door' | 'Lid';
	type GLTFResult = {
		nodes: {
			GlassesModel: THREE.Mesh;
			Cube: THREE.SkinnedMesh;
			Cube_1: THREE.SkinnedMesh;
			Cube_2: THREE.SkinnedMesh;
			Cube_3: THREE.SkinnedMesh;
			Cube_4: THREE.SkinnedMesh;
			Cube_5: THREE.SkinnedMesh;
			TieModel: THREE.SkinnedMesh;
			Floor: THREE.Mesh;
			Wall1: THREE.Mesh;
			Wall2: THREE.Mesh;
			Roof: THREE.Mesh;
			Wall3: THREE.Mesh;
			Door: THREE.Mesh;
			Knob1: THREE.Mesh;
			Knob2: THREE.Mesh;
			WindowFrame1: THREE.Mesh;
			WindowFrame2: THREE.Mesh;
			Wall4: THREE.Mesh;
			WindowFrame3: THREE.Mesh;
			WindowFrame4: THREE.Mesh;
			Grass: THREE.Mesh;
			Road: THREE.Mesh;
			RoadPainting: THREE.Mesh;
			MailboxBase: THREE.Mesh;
			Cube006: THREE.Mesh;
			Cube006_1: THREE.Mesh;
			Lid: THREE.Mesh;
			Opener: THREE.Mesh;
			Pillar: THREE.Mesh;
			Surface: THREE.Mesh;
			Hip: THREE.Bone;
			LeftShoulder: THREE.Bone;
			RightShoulder: THREE.Bone;
			LeftForeleg: THREE.Bone;
			RightForeleg: THREE.Bone;
		};
		materials: {
			Glasses: THREE.MeshStandardMaterial;
			Material: THREE.MeshStandardMaterial;
			Flesh: THREE.MeshStandardMaterial;
			Hair: THREE.MeshStandardMaterial;
			Pants: THREE.MeshStandardMaterial;
			Shoes: THREE.MeshStandardMaterial;
			Shirt: THREE.MeshStandardMaterial;
			Tie: THREE.MeshStandardMaterial;
			OneSidedFloor: THREE.MeshStandardMaterial;
			OneSidedWall: THREE.MeshStandardMaterial;
			SolidWall: THREE.MeshStandardMaterial;
			Wood: THREE.MeshStandardMaterial;
			Gold: THREE.MeshStandardMaterial;
			WindowFrame: THREE.MeshStandardMaterial;
			OneSidedGrass: THREE.MeshStandardMaterial;
			Asphalt: THREE.MeshStandardMaterial;
			RoadPainting: THREE.MeshStandardMaterial;
			Mailbox: THREE.MeshStandardMaterial;
			Void: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/model/testscene2.glb');

	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="EdgarArmature" position={[0, -0.29, 0.01]}>
				<T is={gltf.nodes.Hip} />
				<T is={gltf.nodes.LeftShoulder} />
				<T is={gltf.nodes.RightShoulder} />
				<T is={gltf.nodes.LeftForeleg} />
				<T is={gltf.nodes.RightForeleg} />
				<T.Group name="EdgarModel">
					<T.SkinnedMesh
						name="Cube"
						geometry={gltf.nodes.Cube.geometry}
						material={gltf.materials.Material}
						skeleton={gltf.nodes.Cube.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_1"
						geometry={gltf.nodes.Cube_1.geometry}
						material={gltf.materials.Flesh}
						skeleton={gltf.nodes.Cube_1.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_2"
						geometry={gltf.nodes.Cube_2.geometry}
						material={gltf.materials.Hair}
						skeleton={gltf.nodes.Cube_2.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_3"
						geometry={gltf.nodes.Cube_3.geometry}
						material={gltf.materials.Pants}
						skeleton={gltf.nodes.Cube_3.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_4"
						geometry={gltf.nodes.Cube_4.geometry}
						material={gltf.materials.Shoes}
						skeleton={gltf.nodes.Cube_4.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_5"
						geometry={gltf.nodes.Cube_5.geometry}
						material={gltf.materials.Shirt}
						skeleton={gltf.nodes.Cube_5.skeleton}
					/>
				</T.Group>
				<T.SkinnedMesh
					name="TieModel"
					geometry={gltf.nodes.TieModel.geometry}
					material={gltf.materials.Tie}
					skeleton={gltf.nodes.TieModel.skeleton}
				/>
			</T.Group>
			<T.PerspectiveCamera
				name="Camera"
				far={100}
				near={0.1}
				fov={22.9}
				position={[12.64, 0.83, 12.61]}
				rotation={[-0.04, 0.79, 0.03]}
        makeDefault
			/>
			<T.Mesh
				name="Floor"
				geometry={gltf.nodes.Floor.geometry}
				material={gltf.materials.OneSidedFloor}
				position={[0, -1.8, 0]}
			/>
			<T.Mesh
				name="Wall1"
				geometry={gltf.nodes.Wall1.geometry}
				material={gltf.materials.OneSidedWall}
				position={[4, 0.5, 0]}
			/>
			<T.Mesh
				name="Wall2"
				geometry={gltf.nodes.Wall2.geometry}
				material={gltf.materials.OneSidedWall}
				position={[0, 0.5, 4]}
			/>
			<T.Mesh
				name="Roof"
				geometry={gltf.nodes.Roof.geometry}
				material={gltf.materials.OneSidedFloor}
				position={[0, 2.8, 0]}
			/>
			<T.Mesh
				name="Wall3"
				geometry={gltf.nodes.Wall3.geometry}
				material={gltf.materials.SolidWall}
				position={[0.55, 0.85, -4]}
			>
				<T.Mesh
					name="Door"
					geometry={gltf.nodes.Door.geometry}
					material={gltf.materials.Wood}
					position={[3.37, -0.65, 0.12]}
					rotation={[0, -1.54, 0]}
				>
					<T.Mesh
						name="Knob1"
						geometry={gltf.nodes.Knob1.geometry}
						material={gltf.materials.Gold}
						position={[0.01, 0, 1.39]}
					/>
					<T.Mesh
						name="Knob2"
						geometry={gltf.nodes.Knob2.geometry}
						material={gltf.materials.Gold}
						position={[-0.36, 0, 1.38]}
					/>
				</T.Mesh>
				<T.Mesh
					name="WindowFrame1"
					geometry={gltf.nodes.WindowFrame1.geometry}
					material={gltf.materials.WindowFrame}
					position={[-1.26, 0.22, 0]}
				/>
				<T.Mesh
					name="WindowFrame2"
					geometry={gltf.nodes.WindowFrame2.geometry}
					material={gltf.materials.WindowFrame}
					position={[0.17, 0.22, 0]}
				/>
			</T.Mesh>
			<T.Mesh
				name="Wall4"
				geometry={gltf.nodes.Wall4.geometry}
				material={gltf.materials.SolidWall}
				position={[-4, 0.5, 0]}
			>
				<T.Mesh
					name="WindowFrame3"
					geometry={gltf.nodes.WindowFrame3.geometry}
					material={gltf.materials.WindowFrame}
					position={[0, 0.58, 0.72]}
				/>
				<T.Mesh
					name="WindowFrame4"
					geometry={gltf.nodes.WindowFrame4.geometry}
					material={gltf.materials.WindowFrame}
					position={[0, 0.58, -0.72]}
				/>
			</T.Mesh>
			<T.Mesh
				name="Grass"
				geometry={gltf.nodes.Grass.geometry}
				material={gltf.materials.OneSidedGrass}
				position={[0, -1.9, 0]}
			/>
			<T.Mesh
				name="Road"
				geometry={gltf.nodes.Road.geometry}
				material={gltf.materials.Asphalt}
				position={[0, -1.8, -17.88]}
			>
				<T.Mesh
					name="RoadPainting"
					geometry={gltf.nodes.RoadPainting.geometry}
					material={gltf.materials.RoadPainting}
					position={[0, 0.1, 0]}
				/>
			</T.Mesh>
			<T.Mesh
				name="MailboxBase"
				geometry={gltf.nodes.MailboxBase.geometry}
				material={gltf.materials.Wood}
				position={[0, -0.15, -6.31]}
			>
				<T.Group name="Mailbox" position={[0, 1.08, -0.55]}>
					<T.Mesh
						name="Cube006"
						geometry={gltf.nodes.Cube006.geometry}
						material={gltf.materials.Mailbox}
					/>
					<T.Mesh
						name="Cube006_1"
						geometry={gltf.nodes.Cube006_1.geometry}
						material={gltf.materials.Void}
					/>
					<T.Mesh
						name="Lid"
						geometry={gltf.nodes.Lid.geometry}
						material={gltf.materials.Mailbox}
						position={[0, -0.17, -0.45]}
					/>
					<T.Mesh
						name="Opener"
						geometry={gltf.nodes.Opener.geometry}
						material={gltf.materials.Mailbox}
						position={[-0.2, 0.2, -0.23]}
					/>
				</T.Group>
				<T.Mesh
					name="Pillar"
					geometry={gltf.nodes.Pillar.geometry}
					material={gltf.materials.Wood}
					position={[0, 0.44, -0.36]}
				/>
				<T.Mesh
					name="Surface"
					geometry={gltf.nodes.Surface.geometry}
					material={gltf.materials.Wood}
					position={[0, 0.8, -0.25]}
				/>
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
